INSERT INTO BOOK VALUES(1,'Le Livre de la Purification ','كتاب الطهارة');
INSERT INTO BOOK VALUES(2,'Le livre de la Prière','كتاب الصلاة');
INSERT INTO BOOK VALUES(3,'Le Le livre des Funérailles','كتاب الجنائز');
INSERT INTO BOOK VALUES(4,'Le livre de la Zakât (L’aumône légale)','كتاب الزكاة');
INSERT INTO BOOK VALUES(5,'Le livre du Siyam (le Jeûne)','كتاب الصيام');
INSERT INTO BOOK VALUES(6,'Le livre du Hajj (le Pèlerinage)','كتاب الحج');
INSERT INTO BOOK VALUES(7,'Le livre du Commerce','كتاب البيوع');
INSERT INTO BOOK VALUES(8,'Le livre du Mariage','كتاب النكاح');
INSERT INTO BOOK VALUES(9,'Le livre des Jinayat (les Crimes)','كتاب الجنايات');
INSERT INTO BOOK VALUES(10,'Le livre des Hudud. (les Peines légales)','كتاب الحدود');
INSERT INTO BOOK VALUES(11,'Le livre du Jihâd','كتاب الجهاد');
INSERT INTO BOOK VALUES(12,'Le livre des aliments','كتاب الأطعمة');
INSERT INTO BOOK VALUES(13,'Le livre de serments et vœux','كتاب الأيمان والنذور');
INSERT INTO BOOK VALUES(14,'Le livre de la Juridiction','كتاب القضاء');
INSERT INTO BOOK VALUES(15,'le livre d''emancipation','كتاب العتق');
INSERT INTO BOOK VALUES(16,'Le livre des Généralités','كتاب الجامع');